# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido_pat', models.CharField(max_length=200)),
                ('apellido_mat', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('acuerdo', models.TextField()),
                ('fecha_prox', models.DateTimeField()),
                ('enlaces', models.ManyToManyField(to='web.Enlace')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Entidad')),
            ],
        ),
    ]
