# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enlace',
            name='slug',
            field=models.SlugField(default=' '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entidad',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='slug',
            field=models.SlugField(default='null'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sesion',
            name='acuerdo',
            field=models.TextField(null=True),
        ),
    ]
